# Use templating to enable/disable Horizontal Pod Autoscaling for the navigation-service deployment.
# HPA allows for automatic scaling based on pod CPU metrics
{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: navigation-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: navigation-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
{{- end}}