# Expose the navigation-service internally as a service so the nginx proxy can talk to it
apiVersion: v1
kind: Service
metadata:
  name: navigation-service
spec:
  selector:
    app: navigation-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http