apiVersion: apps/v1
kind: Deployment
metadata:
  name: navigation-service
  labels:
    app: naviation-service
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      app: navigation-service
  template:
    metadata:
      labels:
        app: naviation-service
    spec:
      containers:
      - name: navigation-service
        image: navigation-service:{{ .Values.imageTag }}
        ports:
        - containerPort: 443
          name: https
        resources:
          memory:
            requests: {{ .Values.memory.requests }}
            limits: {{ .Values.memory.limits }}
          cpu:
            requests: 50m
            limits: 100m