# Nginx config file that is loaded into a config map to easily mount into pod.

# Basic configuration which uses the cluster DNS to resolve the IPs of the 
# Rails service and new Navigation Service.

# The proxy will pass any requests with URL prefix of 'navigation/' to the navigation-service service
# The proxy will pass any requests with URL prefix of 'rails/' to the pre-existing Rails app service
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      server {
        listen 80;

        server_name ~^(?<subdomain>.*?)\.;
        resolver kube-dns.kube-system.svc.cluster.local valid=5s;

        location /healthz {
          return 200;
        }

        location /rails/ {
          proxy_pass http://rails-service.default.svc.cluster.local:3000;
        }

        location /navigation/ {
          proxy_pass http://navigation-service.default.svc.cluster.local:8080;
        }
      }
    }