# Ingress object to expose the reverse proxy to traffic from outside of the cluster.
# (Assuming there is already an ingress controller deployed in the cluster)
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  # Using the TLS secret, we can secure the ingress object and terminate TLS here.
  tls:
  - hosts:
      - 'alltrails.com'
    secretName: tls-secret
  rules:
  # All traffic to the alltrails domain and subdomains will be routed through here.
  - host: 'alltrails.com'
    http:
      paths:
      # All traffic will be sent to the nginx-proxy service, which will be sent to the nginx-proxy pod.
      # There, the traffic will be routed to the correct service (navigation or rails app).
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-proxy
            port:
              number: 80