# Expose the nginx-proxy deployment as a service, so the ingress object can route requests to it.
kind: Service
apiVersion: v1
metadata:
  name: nginx-proxy
spec:
  selector:
    app: nginx-proxy
  ports:
  - name: nginx-proxy
    protocol: TCP
    port: 80
    targetPort: 80